### ISSUE TITLE
Suggested and contact us tabs 404

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#110]
On staging.acehelp.com

@breezyboa _a

**Comment by breezyboa** [comment]
Assigning this to @piyushtiw  _a 

`/api/v1/article?url=http://aceinvoice.com/` 
Api returns 
```json
{"errors":"Couldn't find Url"}
```
Since Admin screens are not working in staging
Please assign some entries to root url

Contact us tab is not yet done. This will be fixed with #46

**Comment by piyushtiw** [comment]
Added this URL in DB.
