### ISSUE TITLE
Article Feedback APIs

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#180]
As part of #147

For the backend, we would require the following
- APIs to capture both thumbs up and thumbs down votes on an article
- Capture thumbs down feedback form data

**Comment by neerajdotname** [comment]
> Capture thumbs down feedback form data

In this case what does backend need to send?

**Comment by breezyboa** [comment]
I think just a success/failure message is enough.
Comment and email(if present) will be validated

**Comment by neerajdotname** [comment]
I'm not following you.

1. User clicked on "No". (the article did not help).
2. Client needs to show the form to capture the data.

I'm still not clear on what the api endpoint would look like. Can you elaborate on that.

**Comment by neerajdotname** [comment]
I was not planning to record any upvote or downvote. 
However I think it is a good idea to record it. I will create api for that.

1. User clicks on "downvote/no".
2. Client makes a call to api to increase downvote. Server responds with 200. No content needs to be returned.
3. Client shows form to capture data.

**Comment by breezyboa** [comment]
I was thinking of the following flows

Up vote:
- User clicks on up vote
- Client makes api cal to register a up votel (fire and forget). Server responds with 200

Down Vote:
- User clicks on down vote
- Client makes api call to register a down vote (fire and forget).  Server responds with 200
- Client shows feedback form
- User clicks on submit
- Client validates form and makes api call to submit. Server responds with success or failure if there are no comments.

**Comment by neerajdotname** [comment]
In both the cases no need to wait for the server response to come to show the next thing.
