### ISSUE TITLE
Payload is not a good name for something that server is sending

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#183]
https://monosnap.com/file/8vZKuKaDHbFkGWs5Anr0eh6AVqske7

`addArticle` is returning `createArticlePayload`. Word `Payload` is usually associated with request and not with response.

I looked around but I could not find where the word `Payload` is coming from.

If we look at github api for creating project it returns a `Project` .

https://monosnap.com/file/SpVeJbXD3gP4TEnj3jC4JkZqYVEHjn

https://developer.github.com/v4/mutation/createproject/

**Comment by vipulnsward** [comment]
@prathamesh-sonpatki _a

**Comment by neerajdotname** [comment]
Closing this issue for now since this requires mucking with gem.
