### ISSUE TITLE
Create organization model and api_key for that org

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#20]
https://www.useloom.com/share/f57c22bf5a024b158cb0ff93ab6dc738

@piyushtiw _a

**Comment by piyushtiw** [comment]
@neerajdotname would we keep api_key in the database in encrypted form?

**Comment by piyushtiw** [comment]
can one article belongs_to many organization?

**Comment by piyushtiw** [comment]
This issue is related to issue number 21. Please refer to pull request https://github.com/bigbinary/acehelp/pull/27 for this issue.

**Comment by piyushtiw** [comment]
Merged
