### ISSUE TITLE
Show all articles by default

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#245]
https://monosnap.com/file/H3Ljba3Aa5TEu0ynXjdnpAIsu0MIgO

Do not force user to select a category first to see articles.

**Comment by breezyboa** [comment]
Fix for this should involve using `organization` gql query to fetch all Articles of the current account/org.
Currently  `articles` query is used with `url` parameter which is wrong

**Comment by neerajdotname** [comment]
@breezyboa `articles` query takes `article id` and `url` and both of them are optional. If you do not pass anything then you get all the articles for that organization. However please ensure that you are passing the `api_key` as header.

Here is ruby code.

```
 api_key = request.headers["api-key"]
```

**Comment by neerajdotname** [comment]
PR https://github.com/bigbinary/acehelp/pull/259 is there so closing the issue.
