### ISSUE TITLE
Handle show articles route in rails

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#249]
`/admin/articles/4ba7ddab-defc-4156-beb9-bb4a38618b81`
Should open Article with id `4ba7ddab-defc-4156-beb9-bb4a38618b81`

Elm side routes are taken care of in #237

**Comment by tejaswinichile** [comment]
@breezyboa Right now, its opening `edit` page, instead of that we should show page?
I am trying to understand an issue here.
