### ISSUE TITLE
Add rubocop from wheel and git commit hook

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#25]
@piyushtiw _a

Should be done after https://github.com/bigbinary/acehelp/pull/23 is merged.

**Comment by neerajdotname** [comment]
We removed it from wheel because rubocop was not doing anything. What's the intent here? to fix formatting or something else. Is there any other project which is using rubocop ?

**Comment by vipulnsward** [comment]
> We removed it from wheel

You mean from here(AceHelp) right?

Yes, for auto-format, indentation and other things, they should come up during code-review rubocop should just take care of them.

**Comment by neerajdotname** [comment]
rubocop was not working for me in AceInvoice so I had to remove it. In fact it was creating more problem since I was getting an error which I could not resolve.

Is there any other project where we are using rubocop and benefitting from it ?
