### ISSUE TITLE
After user logs in then take user to the articles page with company id in the url

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#253]
The url should be something like this

```
http://localhost:3000/organizations/085f33987859801c3d07/articles
```

instead of 

```
http://localhost:3000/admin/articles
```

If user is member of many organizations then pick first organization `user.organizations.first`.

**Comment by sudeeptarlekar** [comment]
@neerajdotname by changing `admin/articles` will also have to change other routes in Elm and Rails. As a method in Elm prepends `admin` to each route `Route.elm:46:routeToString`. Should I go ahead and change all of them?

**Comment by neerajdotname** [comment]
@sudeeptarlekar sure go ahead. Don't worry about breaking other things. Breaking things at this stage is ok.
