### ISSUE TITLE
Articles and other resources should have organization/xxxxx in the url just like it is for articles

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#281]
Articles url looks like this http://staging.acehelp.com/organizations/d94618e3c28e2aa62273/articles

Urls url look like this http://staging.acehelp.com/urls

Categories url look like this http://staging.acehelp.com/categories

Tickeets url look like this http://staging.acehelp.com/tickets

Fix all urls to have organization/xxxx in the url.

@sudeeptarlekar _a

**Comment by sudeeptarlekar** [comment]
@neerajdotname aren't we changing routes here...

**Comment by neerajdotname** [comment]
Yes.

I have taken care of it through one PR for each resource.
