### ISSUE TITLE
GraphQL endpoint to handle login request

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#286]
endpoint should accept `email` and `password` and should return `token` if login is valid. If not it should return `error message`.

**Comment by abdul-shajin** [comment]
So far we are not using token based authentication in AceHelp nor we have fields in users table.
by `token` , I'm assuming I need to implement TokenAuthenticatable first, and return the `access_token` . 
Can you confirm @neerajdotname  ?

**Comment by neerajdotname** [comment]
I'm not sure what's the difference between `token` and `access_token`.

Point is that after login client should have some sort of `token`.

**Comment by abdul-shajin** [comment]
Just making sure we are on the same boat..
Thanks

**Comment by abdul-shajin** [comment]
PR merged to master and closing
