### ISSUE TITLE
GraphQL endpoint to accept forgot password

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#287]
It should accept `email` and should return `200` if email was found.
If email is not there the return status `404`.

**Comment by abdul-shajin** [comment]
Do we really need to rely on Status codes?
what I understood is status codes are specific to the http transport and GraphQL doesn't care about the transport.
https://stackoverflow.com/a/51154063/519680
Please let me know I have to stick with codes. @neerajdotname

**Comment by neerajdotname** [comment]
I agree. Don't worry about Status code.

**Comment by tejaswinichile** [comment]
Closing this issue seems PR is merged for the same.
