### ISSUE TITLE
GraphQL endpoint to create a user

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#288]
Endpoint should accept 

* email
* password
* password_confirmation
* Name

should return 200 if user is created. Otherwise should return error message.

**Comment by neerajdotname** [comment]
@tejaswinichile  look it already does the job. If that's the case then just close this issue. If not please make necessary changes.

**Comment by tejaswinichile** [comment]
@neerajdotname It works well, created user and return the error wherever needed. But if we want to have `status code: 200` with the successful saving of user data then I need to make some changes.

this is what we have now: https://monosnap.com/file/kjrOhO82vETh6VgDqgZe3w0uO59Gfv
And this is after I added status code: https://monosnap.com/file/6nUXVhkeAgy9Zzvn3qrOmynyE4ITMb

**Comment by neerajdotname** [comment]
Forget about the status code. I did not realize that GraphQL call is not really REST call. So we need to explicitly send the data to signify whether it was a success or not.
