### ISSUE TITLE
add required code correction.

### ISSUE THREAD

**Issue by sudeeptarlekar** [bigbinary/acehelp#304]
Currently, code in `load_organization` concern is loading organization by default which is making code work on local but it fails when on staging.

```
before_action :load_organization
...

def load_organization
    api_key = request.headers["api-key"] || params["organization_api_key"]

    if api_key.blank?
      if Rails.env.development?
        @organization = Organization.first
        return
      end

      render_unauthorized(unathorized_error_message)
    else
      @organization = Organization.find_by(api_key: api_key)
      render_unauthorized(unathorized_error_message) && return if @organization.blank?
    end
end

```

also after making an change `localhost:3000/graphql/playground` should continue to work.

**Comment by tejaswinichile** [comment]
Checking case of no organization present on sign up , after merge of #296

**Comment by tejaswinichile** [comment]
Refer #296  Resolved it in same. As after sign up when the user creates the organization at that time we don't have organization API key present, then we should update context accordingly and pass organization key to the main model.
