### ISSUE TITLE
Add user to the organization

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#312]
GraphQL endpoint to add a new user to the organization.

accepts : email (required), name(optional). 

If a user with given email already exists then add that user to the org.

If a user with that email does not exist then create a user with that email and then add that user to the org.

**Comment by abdul-shajin** [comment]
FYI,
When we have to create a user, password field have to be filled and for now, I have given a token generated by Devise itself. 
When we handle the complete Onboarding process, we may have to deal this differently

**Comment by tejaswinichile** [comment]
@abdul-shajin Then we should send password reset mail to the user, right?
cc : @neerajdotname

**Comment by neerajdotname** [comment]
See what AceInvoice does. Do the same.

**Comment by tejaswinichile** [comment]
In AceInvoice they do send one welcome email after adding of the user. @abdul-shajin  Please check this and make necessary changes.
