### ISSUE TITLE
Add a user to the team

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#314]
Ref https://github.com/bigbinary/acehelp/issues/312

**Comment by tejaswinichile** [comment]
We are handling it like `ace-invoice` Add new team member in team listing page of the organization.

**Comment by tejaswinichile** [comment]
@neerajdotname Are we assigning a role to the user here?

**Comment by neerajdotname** [comment]
We will have roles in future. For now we can ignore it.
