### ISSUE TITLE
Send user agent when a ticket is created

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#317]
Below "Color Depth", you will see "full user agent".

whatsmybrowser.org/b/PZRUBQD

Client should pass "full user agent" to backend.

**Comment by abdul-shajin** [comment]
Do we really need this?
What's the difference from this manually constructed user_agent and what we can get from `request.user_agent`

@neerajdotname

**Comment by neerajdotname** [comment]
Good point. Manually constructed user_agent is not needed.
