### ISSUE TITLE
Followup Task: Add api-key error handler in AssignUserToOrganizationMutations

### ISSUE THREAD

**Issue by abdul-shajin** [bigbinary/acehelp#324]
this is a TODO task
Need to add api-key error handler to AssignUserToOrganizationMutations once PR #323  is through

**Comment by neerajdotname** [comment]
Is it not possible to handle api-key error in a generic way since this is a cross cutting concern applicable to all code.

**Comment by abdul-shajin** [comment]
I have raised the PR assigned you #333 
What I tried to achieve is, if someone try to accept context[:organization] and if the controller did not set the key, it will raise a GraphQL exception that would return proper GraphQL errors with no data. 
@neerajdotname

**Comment by abdul-shajin** [comment]
PR merged and closing
