### ISSUE TITLE
GraphQL mutation : add a note to a ticket

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#327]
A note is a private information that an agent puts for personal or for other agents to see. Customer should not see any note.

mutation should accept

* note (text area)
* agent_id (person who is posting note)
* ticket_id

**Comment by abdul-shajin** [comment]
Ref:  #348

**Comment by tejaswinichile** [comment]
PR #[348](https://github.com/bigbinary/acehelp/pull/348)
