### ISSUE TITLE
Auto assign ticket to the agent who responded to the ticket.

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#330]
Ref https://github.com/bigbinary/acehelp/wiki/Triggers-for-Tickets

When a "reply to customer" is posted then see if that ticket has been assigned to any agent or not. If not then assign that ticket to the agent who posted reply to customer.

**Comment by abdul-shajin** [comment]
Is reply to customer means post-comment-to-ticket mutation?
@neerajdotname

**Comment by neerajdotname** [comment]
"Reply to customer" means when an agent posts a comment.
