### ISSUE TITLE
PR Builds give `Unauthorized request: Missing or invalid API Key` Errors

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#349]
When loging into admin section on PR builds
it always gives a `Unauthorized request: Missing or invalid API Key` 

https://monosnap.com/file/FWzDGNil50nKlQiUAPBkriFEuxoIA7

**Comment by tejaswinichile** [comment]
Seems We have hardcoded staging URL here, so whenever we send the request it's sending to http://staging.acehelp.com/ and the organization which we are requesting is not present on staging DB https://github.com/bigbinary/acehelp/blob/master/app/javascript/Admin/Admin/Request/Helper.elm#L42

I'll figure out the way by which we can access the current Heroku URL. Not taking it on priority though.
cc : @breezyboa

**Comment by tejaswinichile** [comment]
We can't use this in ruby way `https://#{HEROKU_APP_NAME}.herokuapp.com/` , we need to set this with `process.env` in `node` to access `HEROKU_APP_NAME`. And then we will have to send this to every graphQL request by using `ProgramWithFlags` set in `Elm`.

**Comment by sudeeptarlekar** [comment]
@sudeeptarlekar _a
