### ISSUE TITLE
Update UI for Team listing page

### ISSUE THREAD

**Issue by tejaswinichile** [bigbinary/acehelp#366]
refer: https://github.com/bigbinary/acehelp/pull/360#discussion_r208508446

We need to show all action button on hover in Team listing page. 
Buttons are there in place need to fix the UI for the same.

**Comment by Shrikant9** [comment]
@breezyboa Isn't this similar to [#358](https://github.com/bigbinary/acehelp/issues/358)?

**Comment by tejaswinichile** [comment]
@Shrikant9 Yes those are same. We want to make it consistent.
Removing Url from this issue.

**Comment by breezyboa** [comment]
@Shrikant9 we need to apply the same styles as in Url tab to Team tab
