### ISSUE TITLE
Update List all tickets query to remove deleted ones

### ISSUE THREAD

**Issue by abdul-shajin** [bigbinary/acehelp#374]
Update GraphQL Queries that fetches all tickets/ tickets based on their status to handle the deleted records

This task should be done after #373

**Comment by tejaswinichile** [comment]
@abdul-shajin Do we want to handle this as only show not deleted records?

**Comment by abdul-shajin** [comment]
@tejaswinichile 
Yes, kind of default_scope to avoid all non-null-deleted_at records like we discussed that day

**Comment by tejaswinichile** [comment]
@abdul-shajin #373 Handles the same, this issue got resolved in the same implementation.
Closing this ticket.
