### ISSUE TITLE
Add Delete article button and update the UI

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#382]
Restyle the interface. Keep the styling similar to Urls tab. 

Ref image:
<img width="1060" alt="url-list" src="https://user-images.githubusercontent.com/7039911/43772809-0add373c-9a61-11e8-9601-737c26153d92.png">

Also, add a Delete button to delete an Article.

**Comment by pranavrajs** [comment]
@pranavrajs _a
