### ISSUE TITLE
Add functionality to fetch user details and update user in Ruby.

### ISSUE THREAD

**Issue by Shrikant9** [bigbinary/acehelp#393]

**Comment by tejaswinichile** [comment]
We don't need to update team member yet.
If we want to update member's role we need to confirm that first.

**Comment by tejaswinichile** [comment]
@breezyboa Can you confirm the above requirement, If we are updating team member's data or not.

**Comment by tejaswinichile** [comment]
@breezyboa _a Need your confirmation on above requirement If we don't need to update team member, close this ticket.

**Comment by breezyboa** [comment]
If this is about updating a users role. We do not need it right now

**Comment by tejaswinichile** [comment]
Closing this issue.
