### ISSUE TITLE
Not able to create a team member

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#409]
https://monosnap.com/file/vGDXeqGpLbFW6qTGmvPIJBLzs3UTYv

First I got the error message that "email can't be empty". So I provided email.

Now I got this error.

**Comment by tejaswinichile** [comment]
> https://monosnap.com/file/vGDXeqGpLbFW6qTGmvPIJBLzs3UTYv 
<< Not able to set current_user on staging
