### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#431]
- [ ] In article listing page move "New Article" button to the top. Label the button to "+ Article"
- [ ] In url listing page label "New Url" button as "+ Url"
- [ ] In Category listing page label "New Url" button as "+ Category"

**Comment by Shrikant9** [comment]
@breezyboa 
The button already seems to be on top. That is, for all the three pages: Article, Url, and Category.
Am I supposed to change its position? Or just change the text?

<img width="750" alt="screen shot 2018-08-21 at 12 52 14 pm" src="https://user-images.githubusercontent.com/12266517/44386896-80f81780-a541-11e8-8b5c-cf7addd8736a.png">

**Comment by breezyboa** [comment]
@Shrikant9 if it's on top then its fine. We just need to change the text then

**Comment by Shrikant9** [comment]
@breezyboa 
- [x]  In article listing page, label the button to "+ Article"
- [x]  In URL listing page, label the button to "+ Url"
- [x]  In Category listing page, label the button to "+ Category"
