### ISSUE TITLE
Mark a Category as online or offline

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#433]
Admin users should be able to mark a Category as online or offline.
If a category is marked offline then all articles under the category should be marked offline
If even one article is marked online under a category then the category should be marked online

To be done after #428

**Comment by tejaswinichile** [comment]
- [ ] Category status update mutation -Rails
- [ ] Update Category status - Elm

**Comment by tejaswinichile** [comment]
Closing this issue, we have PR raised for the same.
