### ISSUE TITLE
Categories query does not return articles associated with category

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#442]
Graphql Query
```
query {
  categories {    id    name    articles {      id    title    }  }}
```

Steps to reproduce:
- Login to an account in Admin panel
- Create a category
- Create couple of articles and associate it to the category
- Copy paste the js snippet fro settings in a html page
- Open Page. Click on acehelp button goto library tab. 
- Click on the category. Notice no results are displayed. Check the network response and notice not articles are returned for specified category

**Comment by tejaswinichile** [comment]
The issue here with article creation, as we have seen in @breezyboa local, we are not able to create the article or associate category to article.
Issue #451 will resolve this.

**Comment by tejaswinichile** [comment]
@breezyboa Can you check is this issue still appears on your machine (on master). try to assign category again to an article then check if it's loading articles.

**Comment by tejaswinichile** [comment]
This working fine but facing new issue https://github.com/bigbinary/acehelp/issues/473
