### ISSUE TITLE
Category success message stays on forever

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#452]
- Create a new category
-  Navigate to different pages
- Notice success message is not cleared

https://monosnap.com/file/kA0YHUXyI1tAGGVpLS3B2OR6DMDvGw

**Comment by tejaswinichile** [comment]
We need to introduce close button, right now I have added removeNotification onClick of message only.
And Yes one thing missed out is to update flashMessage after navigation.

**Comment by neerajdotname** [comment]
Just like AceInvoice success message should auto disappear. That will remove the need for having a close button.

**Comment by tejaswinichile** [comment]
Yeah that can also be done 👍

**Comment by tejaswinichile** [comment]
Closing this issue as PR is up for the same.
