### ISSUE TITLE
Handle login page route

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#458]
Refer: https://github.com/bigbinary/acehelp/pull/457#issuecomment-415378957

**Comment by tejaswinichile** [comment]
- [x]  redirect to login page after successful sign-up
- [x]  redirect to organization page after login response

remove curent_user check and handle every request with auth token << To be done after #435 gets merged

**Comment by tejaswinichile** [comment]
Handled this inside https://github.com/bigbinary/acehelp/pull/435/commits/7bce985130c17b04f2ce95e7948bc1a27c43bcd3
closing this issue
