### ISSUE TITLE
Sign up link does not work when already signed in 

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#462]
If a user is already signed in and clicks on the sign-up button in the homepage to create a new account, User gets logged into the current account.

**Comment by tejaswinichile** [comment]
@breezyboa What should be the ideal case here? A user should be logged out from the previous session and should get logged in to the new account? Or should be able to access two accounts from the same browser?

**Comment by breezyboa** [comment]
@tejaswinichile no, I do not think the user should be able to access two accounts from the same browser. Since when the user clicks on the "sign up" button his intentions are quite clear that he wants to create a new account. Can we just log the current user out as he navigates to sign up page?

**Comment by tejaswinichile** [comment]
@breezyboa Yes we can do that 👍

**Comment by tejaswinichile** [comment]
@breezyboa So If the user is already logged in then the sign_in link will take him/her to the main page.

**Comment by breezyboa** [comment]
@tejaswinichile I think that's the default behavior anyway right now.
The issue was for sign up link, and it is that same behavior for sign up also currently. So I think we can close this issue

**Comment by tejaswinichile** [comment]
Yeah, It's working for sign-up too.  Closing this issue 👍
