### ISSUE TITLE
Error message needs to be better

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#483]
https://monosnap.com/file/G5L6IMBy0RDSr0tsq8Gg9j6oc4ybOo

Error message needs to be "Email is already registered. Please try a different email".

@Shrikant9 _a

**Comment by Shrikant9** [comment]
@tejaswinichile I get the following when I call the signup query with existing email:
```
{
  "data": {
    "signup": {
      "user": null
    }
  }
}
```

Can this be changed to an error?

**Comment by tejaswinichile** [comment]
@Shrikant9 Let me check that.
