### ISSUE TITLE
After registering I'm not able to login

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#484]
I tried three times and every single time after registering I'm not able to login.

@Shrikant9 _a

**Comment by Shrikant9** [comment]
@breezyboa 
Are we resolving this issue in [#435](https://github.com/bigbinary/acehelp/pull/435)?
Is there anything additional I am supposed to do from the Elm side?

**Comment by breezyboa** [comment]
@Shrikant9 no this should be have been working. Can you investigate and see whats going on?

**Comment by Shrikant9** [comment]
@breezyboa 
I checked the Ruby-based authentication, and it's working fine. The one that doesn't work right now is the Elm based login, I can see the fix [here](https://github.com/bigbinary/acehelp/pull/435/files#diff-2bc8a2b43c1b3cd65e5916c2e7338445R799)
