### ISSUE TITLE
GraphQL API returns an error while retrieving Articles

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#488]
https://monosnap.com/file/Epr6wnOArAj80QLDecTy11gmFkXeZG

**Comment by tejaswinichile** [comment]
Handled in #490

**Comment by breezyboa** [comment]
Reopening this issue as its still happening in the staging environment

**Comment by tejaswinichile** [comment]
@breezyboa _a Please have a look at staging instance. And verify the issue from your side.
We need to handle auto-delete cookies after expiry_time I will be creating the new issue for the same.
