### ISSUE TITLE
Add Enable/Disable widget to settings

### ISSUE THREAD

**Issue by ritesh404** [bigbinary/acehelp#494]
Widget should have a set of settings to customize it.
To start with we can have "Enable Widget" setting.
When this setting is toggled "on". the AceHelp "?" button should display on the users page
When this setting is "off" the AceHelp "?" button should not be displayed

<img width="1207" alt="settings" src="https://user-images.githubusercontent.com/7039911/45026795-01983700-b05d-11e8-895a-a2139ada5d9c.png">

The scope of this issue is only to save the settings.

**Comment by breezyboa** [comment]
Toggle button codepen: https://codepen.io/aanjulena/pen/ZLZjzV

**Comment by tejaswinichile** [comment]
PR #515 is up for the same.
