### ISSUE TITLE
Error message is not correct

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#504]
https://monosnap.com/file/P5ons80ydcyiMHDr7lolGDshH90kIL

@tejaswinichile _a

**Comment by tejaswinichile** [comment]
Right now for all saving mutation, we have introduced  `Maybe object` that's why errors are not rendering at all if anything goes wrong.

**Comment by tejaswinichile** [comment]
@ritesh404  I will need your help in this to handle the above condition.
