### ISSUE TITLE
When user is signing up, don't show sign in page after that

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [bigbinary/acehelp#534]
Right now, after the user signs up, we show sign in page. IMO we can just log in the user and directly show the admin page.

@neerajdotname _A

**Comment by neerajdotname** [comment]
I agree. I did not create this issue earlier because the team was already struggling with login issue.

@tejaswinichile _a

**Comment by prathamesh-sonpatki** [comment]
This is completed.
