### ISSUE TITLE
Elm side test cases

### ISSUE THREAD

**Issue by tejaswinichile** [bigbinary/acehelp#543]
Need to have test cases for all elm side pages

**Comment by neerajdotname** [comment]
For now we can do manual tests. 

Like all other projects we would be doing cypress tests.

If we write only elm tests then that will test only the elm part. Cypress test will test full interaction including hitting the backend. This is the same reason why we do not write tests only for React.js.

**Comment by prathamesh-sonpatki** [comment]
I agree 👍 We can write cypress tests to cover basic flows.
