### ISSUE TITLE
Error message needs to be clearer

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#560]
https://monosnap.com/file/OowrwKHU1UfZyVHrO902oTXUkk2r2j

It should say "Email is required".

Why can't we use `require` html attribute which will not allow a form to be submitted if required fields are not filled in. Is this not supported by elm ?

It should do same for org name. I mean make that field a required field.

@ritesh404 _a

**Comment by ritesh404** [comment]
@neerajdotname yes we should be able to use `required`
Will fix this
