### ISSUE TITLE
Getting error from Elm

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [bigbinary/acehelp#576]
https://www.useloom.com/share/d9a9d85f006a4ebab436e789cd31ce94

I am not sure if this is happening because of browser extension or not because @tejaswinichile is not facing it.

@ritesh404 _a

**Comment by prathamesh-sonpatki** [comment]
This is definitely related to extensions. It does not happen in incognito mode.

**Comment by ritesh404** [comment]
@prathamesh-sonpatki yes most like it would be extension related. There have been such cases reported in other elm projects as well. 

We can have Sentry or something integrated to get know about these. But there won't be much we can do about it I think
