### ISSUE TITLE
Enable cross origin resource sharing

### ISSUE THREAD

**Issue by breezyboa** [bigbinary/acehelp#58]
https://monosnap.com/file/MXJmlLrPbeeDBONoJ6y37yOoCLnSqw

**Comment by vipulnsward** [comment]
@piyushtiw _a

**Comment by piyushtiw** [comment]
@breezyboa can you share web-service-consumer-site URL?

**Comment by piyushtiw** [comment]
@vipulnsward what are the domain for which I have to enable the cors or should I enable it for all domain?

**Comment by neerajdotname** [comment]
```
*.herokuapp.com
*.acehelp.com
```

Let's start with those two. More can be added later.

**Comment by piyushtiw** [comment]
merged
