### ISSUE TITLE
Is flip not defined in elm 0.19 

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#581]
https://github.com/bigbinary/acehelp/blob/fb45a8cbae54a62448ec8ccf352edac3c9b17eba/app/javascript/Admin/Helpers.elm#L59

https://package.elm-lang.org/packages/elm-lang/core/latest/Basics#flip

@ritesh404 _a

**Comment by ritesh404** [comment]
@neerajdotname flip was removed in 0.19

The link being referred to is from 0.18. Notice the `elm-lang` package
Core libraries have been moved under `elm` now

https://package.elm-lang.org/packages/elm/core/latest/

**Comment by neerajdotname** [comment]
Can't believe that flip is removed. I have not worked in elm long enough to comment on it but it seemed useful.

https://www.reddit.com/r/elm/comments/992pxz/elm_019_released/e4mg9ce/
