### ISSUE TITLE
Is there no active integration anymore?

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#597]
I see no help widget on any pages of this example site:
https://careforever-for-acehelp.herokuapp.com/pages/about

Where are the live widget examples?

@tejaswinichile _A

**Comment by neerajdotname** [comment]
It's here https://github.com/bigbinary/bigbinary-website/pull/789

Actually we should be using https://github.com/bigbinary/careforever-for-acehelp . However I wanted to test if using the widget in an existing application interferes with anything or not.

**Comment by ritesh404** [comment]
We need to update the APIKEY in careforever-for-acehelp
Currently it has an invalid one
 
<img src="https://monosnap.com/image/APgATVj8wrPs9Zd5gu9D4fNst9MjVh">

**Comment by tejaswinichile** [comment]
After acehelp-staging deployment, we need to be sure that we update `ApiKey` on this app.

**Comment by neerajdotname** [comment]
> After acehelp-staging deployment, we need to be sure that we update ApiKey on this app.

Not sure what you mean by this. Whenever we merge a PR to master staging app is deployed. If ApiKey is fixed then add to sample data to override the apikey with the apikey given to careforever app.

It's just not practical to keep updating the apikey after every PR merge.

**Comment by tejaswinichile** [comment]
We will be removing `rake db:drop` command from release to fix this.

**Comment by vipulnsward** [comment]
@tejaswinichile please close issues, after they are fixed, in this case after the sample site starts showing the integration.

**Comment by vipulnsward** [comment]
I see that it has been fixed now.
