### ISSUE TITLE
Client side validation for team form

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#600]
https://monosnap.com/file/aKNqP3sHtXVywMBbFIrC3qrPATWe5O

No need to hit server for missing required fields. Use html attribute `required` for client side validation.

@vishaltelangre _a

**Comment by vishaltelangre** [comment]
@neerajdotname _a 

On form submission, no request is issued to the server for form validation.

Only required field on the form for adding a team member is `Email` which gets validated on the client side itself using the function `validateEmail`.

https://github.com/bigbinary/acehelp/blob/72c8b43f9fb2954a176f55b51ed8ee43e416ce03/app/javascript/Admin/Page/Team/Create.elm#L36

Do we still want to use the HTML attribute `required` here?

**Comment by neerajdotname** [comment]
Sure. If a field is required then having a `required` attribute is a good think I think. Unless someone can see a downside of doing that.

**Comment by ritesh404** [comment]
@vishaltelangre  We don't use a typical form element in most places. The fields need to be under a form for the `required` attribute to work. We can either convert the whole thing to a form and add the required attribute, which would give us a nice animated alert for free. Or we can just compose `validateEmail` with `validateEmpty` in the Field type to do both validations.

In the case of Url tab we converted it to a form I think we can do the same here also
