### ISSUE TITLE
Not able to create a team member

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#601]
https://monosnap.com/file/xBCsSjHxdRjwSmNTUyPmougakJxWPj

**Comment by tejaswinichile** [comment]
Not able to find the current_user set in context in `graphql_controller`

**Comment by tejaswinichile** [comment]
https://github.com/bigbinary/acehelp/commit/bb488dd8f009b713175b67caaa31e566c7f16805
This change fixes the issue.
