### ISSUE TITLE
UpdateArticle mutation Input type is incorrect

### ISSUE THREAD

**Issue by ritesh404** [bigbinary/acehelp#611]
The input type takes only one category_id and url_id. it should take a list of selected urlids and categoryId and associate those urls and ids with the article
```
type UpdateArticleInput {
  clientMutationId: String
  id: String!
  category_id: String
  url_id: String
  title: String!
  desc: String!
}
```

**Comment by tejaswinichile** [comment]
As it's calling in every change of category select it's sending only one selected category id from elm side, I will be changing it as we are handling it in createArticleInput.

cc @ritesh404

**Comment by ritesh404** [comment]
There is a slight delay added so that if the user wants to select multiple categories or urls they can do so. The call is only made after the delay and in between if the user selects or deselects anything the delay is reset this allows us to send a list of categories/urls
