### ISSUE TITLE
Category name should be editable in listing page

### ISSUE THREAD

**Issue by ritesh404** [bigbinary/acehelp#624]
To edit the category name user has to click on edit category button and then goto a new page to edit the name.

Instead, the user should be able to edit the category name in the listing itself.
User should be able to double click on the category name or we can also show a small pen/edit icon when the user hovers the mouse pointer on the row - on click of the edit icon the user should be able to edit the category name

Note: use fontawesome svgs for edit icon

![category-edit](https://user-images.githubusercontent.com/7039911/46011510-b4e7cf00-c0e3-11e8-9551-485f2535246f.png)
![category-edit-2](https://user-images.githubusercontent.com/7039911/46011511-b5806580-c0e3-11e8-87f8-310c62178f3b.png)

**Comment by vishaltelangre** [comment]
@chiraggshah _a
