### ISSUE TITLE
Data should be prepopulate on contact us page if userinfo exists

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#64]
It would work something like this.

```
AceHelp.userInfo({
 name: "Sam Smitht",
  email: 'sam.smith@example.com'
})
```

References

https://developer.helpscout.com/beacons/javascript-api/#identify

Similarly intercom has  `window.intercomSetting`.

![intercom](https://user-images.githubusercontent.com/6399/40892651-cdf0ec50-674e-11e8-9550-83a60ba8cb59.png)

**Comment by vipulnsward** [comment]
@breezyboa _a
