### ISSUE TITLE
Update URL creation page to handle URL patterns

### ISSUE THREAD

**Issue by ritesh404** [bigbinary/acehelp#670]
Currently, we use a string to represent a URL.
We need to change this to a URL pattern.

A URL pattern would be matched by the server against the incoming URL sent by the widget to serve suggested articles

A URL Pattern can be one of the following

URL Contains "some pattern"
URL Ends With "some pattern"
URL is "some absolute URL"
Note that we will be using "*" to represent a wildcard

This isssue is to update the URL Create page to handle URL patterns instead of just absolute URLs

**Comment by vishaltelangre** [comment]
@ritesh404 The title of this issue is confusing. I think we need to update the view for adding URL patterns, but I am not sure about it.

Please update the title appropriately and also describe in brief what changes exactly needs to be made to address this issue.
