### ISSUE TITLE
Remove authenticity check skip method

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#675]
- [x] Get rid of the skip from ApplicationController and add elm-rails to bring back csrf
- [x] Create separate routes/auth check/csrf checks for Widget methods.

**Comment by vishaltelangre** [comment]
@tejaswinichile _a Please work on to retrieve the CSRF token from the meta tag which is available in the template rendered by Rails and pass it as a header along with the every request made from Elm or JavaScript code.

We will look into it in more detail in the v2 release.

**Comment by tejaswinichile** [comment]
Closing this as PR is up for the same.
