### ISSUE TITLE
Suggestion / request: use Dependabot to keep gems up-to-date

### ISSUE THREAD

**Issue by greysteil** [bigbinary/acehelp#677]
First of all, thanks for AceHelp!

I've got a suggestion / request: would you be up for using [Dependabot](https://dependabot.com) to automatically create dependency update PRs for this repo? I ran it against my fork and it generated [these PRs](https://github.com/greysteil/acehelp/pulls). I've ported the `nokogiri` one across to this repo (#676), which is for the vulnerability announced last night.

I built Dependabot, but I'm honestly only suggesting it because I hope it can save you some time. Obviously having open source repos using it helps boost its profile but if it's not helpful to you then it's not really worth anything.

You can install it from [here](https://github.com/apps/dependabot) or [here](https://github.com/marketplace/dependabot) if you decide to give it a try. It's been through GitHub's security testing (to be allowed in the GitHub Marketplace) and is used by a few thousand organisations, and the source code is [here](https://github.com/dependabot/dependabot-core).

:octocat:

**Comment by greysteil** [comment]
Thanks for the merge and the 👍 @tejaswinichile. Any more info I can provide on the above?

**Comment by tejaswinichile** [comment]
@greysteil We will have [Dependabot](https://dependabot.com/) in this repository. We will let you know if we stuck somewhere while integrating it.
Thanks for the suggestion.

**Comment by greysteil** [comment]
Awesome! I'll try to help out with the initial PRs - let me know once it's added and I'll look through.

**Comment by vishaltelangre** [comment]
@tejaswinichile _a If this requires more efforts than anticipated, please assign it to me. I will take care of this.

**Comment by tejaswinichile** [comment]
Resolved, followed https://github.com/apps/dependabot
