### ISSUE TITLE
Delete temporary article, when user move away from create article page.

### ISSUE THREAD

**Issue by tejaswinichile** [bigbinary/acehelp#685]
When user navigate away from article create page without saving the data.
Delete the article along with the attachments.

**Comment by vishaltelangre** [comment]
@tejaswinichile If you have not started work on this, can I take this up?

**Comment by tejaswinichile** [comment]
Yeah. I haven't. You can take this up.

**Comment by vishaltelangre** [comment]
@vishaltelangre _a
