### ISSUE TITLE
Create graphQL mutation to map Categories to URL Patterns

### ISSUE THREAD

**Issue by ritesh404** [bigbinary/acehelp#689]

**Comment by tejaswinichile** [comment]
- [ ]  Add association many-to-many for category and URL pattern
- [ ]  Remove direct articles to URLs association
- [ ] Update search article query
- [ ] Update Mutation to add/update article(remove adding URLs to article)
- [ ] Update URL type and article type to fetch articles and URLs data respectively
- [ ] Update category type to fetch URLs

**Comment by tejaswinichile** [comment]
@ritesh404 https://monosnap.com/file/hrYXEXCQpSqI1wnbtESaPX9eXcdXBK

**Comment by tejaswinichile** [comment]
Since we will not be having a direct relationship between the article and URLs.
I will be removing the whole article_urls association from the app.
cc @vishaltelangre

**Comment by tejaswinichile** [comment]
All the to-do are done for this issue. And push in branch [here](https://github.com/bigbinary/acehelp/compare/689-URL-map-to-category?expand=1)
