### ISSUE TITLE
Build failing on CircleCI

### ISSUE THREAD

**Issue by sudeeptarlekar** [bigbinary/acehelp#69]
https://circleci.com/gh/bigbinary/acehelp/90#usage-queue/containers/0

Error : 
Running /home/circleci/acehelp/node_modules/.bin/elm-make /home/circleci/acehelp/app/javascript/Main.elm --yes --warn --debug --output /tmp/11854-4422-1kv3sx8.b8x5h.js
Too long with no output (exceeded 10m0s)

@sudeeptarlekar _a

**Comment by rkr090** [comment]
Fixed in https://github.com/bigbinary/acehelp/pull/71
