### ISSUE TITLE
Upgrade sprockets / Fix CVE

### ISSUE THREAD

**Issue by vipulnsward** [bigbinary/acehelp#723]
@vishaltelangre _A

**Comment by vipulnsward** [comment]
I do not the resolution. Please follow the discussion here: https://github.com/rails/sprockets/issues/565

**Comment by vishaltelangre** [comment]
Thank @vipulnsward  for the link to the discussion.

Downgrading to a really old version does not sound a good idea. I think we should wait for the stable v4.0 release or switch to the current beta version 4.0.0.beta8.

We use Webpacker to precompile the assets, therefore our exposure to that CVE should be relatively small.

Let me try out beta version of the 4.0 release and see if everything works or not. If works, we can switch to it.
