### ISSUE TITLE
Production instance

### ISSUE THREAD

**Issue by neerajdotname** [bigbinary/acehelp#731]
@vishaltelangre _a I have added https://app.acehelp.com . This will be production instance.

You have been added to heroku collaborators for production instance. So you can setup redis, bonsai and other things.

**Comment by vishaltelangre** [comment]
@tejaswinichile @neerajdotname I think these URLs are not going to work for the widgets installed from the production app.

https://github.com/bigbinary/acehelp/blob/31d56c2e3421222c8e0e7c4022538681b212baa9/app/javascript/Client/Request/Helpers.elm#L62-L72

I assume that Heroku must be providing an environment variable containing the base URL or subdomain of the app. If it does, we will need to use it and pass down to Webpacker while it pre-compiles the assets.

**Comment by tejaswinichile** [comment]
@vishaltelangre How about we will have staging environment set for webpacker so it will not fall back to production environment.
Then we can use above implementation with production `base_url`

**Comment by vishaltelangre** [comment]
I do not like the idea of hard-coding URLs into the static assets.

I have found the following environment variables available to the dynos of various apps.

For review apps, we get the following.

```
$ heroku run printenv --app acehelp-staging-pr-692
[...]
HEROKU_APP_NAME=acehelp-staging-pr-692
[...]
```

For staging app, we get the explicitly set environment variable. 
```
$ heroku run printenv --app acehelp-staging
[...]
HEROKU_APP_URL=https://staging.acehelp.com/
[...]
```

For the production app, we get the explicitly set environment variable. 
```
$ heroku run printenv --app acehelp-production
[...]
HEROKU_APP_URL=https://app.acehelp.com/
[...]
```

We can use these environment variables to provide an appropriate base URL to be prefixed with the API endpoints in the widget's Elm code.

**Comment by tejaswinichile** [comment]
@vishaltelangre Yeah we can do that, we are handling same in admin side app.

**Comment by vishaltelangre** [comment]
Thanks. I am working on it.

**Comment by vishaltelangre** [comment]
I have added "Bonsai Elasticsearch" and "Redis To Go" add-ons to the app.acehelp.com app on Heroku.

I am going to take care of the base URL related changes as discussed above separately in https://github.com/bigbinary/acehelp/issues/737.

Closing this issue.
