### ISSUE TITLE
Change APIs in graphql

### ISSUE THREAD

**Issue by piyushtiw** [bigbinary/acehelp#78]

**Comment by piyushtiw** [comment]
@rkr090 I am facing some issue while writing a unit test for the mutations in Graphql. For testing, I am making a client and send the request to the server(for this I have to start the server). Can you please suggest me some better solution?

**Comment by piyushtiw** [comment]
@rkr090 can I use RSpec only and change all the Minitest in Rspec?

**Comment by neerajdotname** [comment]
> change all the Minitest in Rspec?

Did you mean "change all the existing tests using Minitest to Rspec" ?
