### ISSUE TITLE
Issue with knapsack:minitest

### ISSUE THREAD

**Issue by rkr090** [bigbinary/acehelp#87]
https://github.com/bigbinary/acehelp/pull/76#discussion_r194299729

```
I have used Graphlient gem for testing. If I run the test with knapsack:minitest it gives error "Graphlient not found".
```

**Comment by rkr090** [comment]
@piyushtiw _a you can also look how to make ```knapsack:minitest``` work with ```Graphlient```

**Comment by piyushtiw** [comment]
merged
