### ISSUE TITLE
Add cors for https://acehelp-staging-pr-85.herokuapp.com/ origin.

### ISSUE THREAD

**Issue by piyushtiw** [bigbinary/acehelp#92]

**Comment by rkr090** [comment]
@piyushtiw @vipulnsward @breezyboa I'm very confused with these CORS issues, why do we need it when we are not making any cross-origin requests?

The code loaded on staging will make the call to the API on staging, same for review apps, where is the cross-origin request? If the scheme in the URL is **HTTP**, then the API request should also be made with HTTP scheme

If we open the API for one specific doamin, we need to allow that domain.
When we open the API for public, we will need to add 'Access-Control-Allow-Origin : *' to allow others to make the request.

**Comment by vipulnsward** [comment]
We will need it when we start allowing accessing on TP sites, that embed our JS code.

Anyway, lets kill cors for now

**Comment by rkr090** [comment]
I believe the main issue which triggered all this is https://github.com/bigbinary/acehelp/issues/97

We should not make API call to staging from review apps.
